name: 🐞 Bug Report
description: Report something that is not working
body:
  - type: checkboxes
    attributes:
      label: Prerequisite
      options:
        - label: I've confirmed that my **Obsidian** is up to date.
          required: true
        - label: I've confirmed that my **Obsidian installer** is up to date with the [latest GitHub release](https://github.com/obsidianmd/obsidian-releases/releases/latest).
          required: true
        - label: I've confirmed that **Lumin** is up to date with the [latest GitHub release](https://github.com/yixuan-space/obsidian-lumin/releases/latest).
          required: true
  - type: input
    attributes:
      label: Obsidian version
      placeholder: e.g., 1.11.7
    validations:
      required: true
  - type: input
    attributes:
      label: Obsidian installer version
      placeholder: e.g., 1.11.7
    validations:
      required: true
  - type: input
    attributes:
      label: Lumin version
      placeholder: e.g., 3.2.0
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      placeholder: macOS 26.3, Windows 11 25H2, iOS 26.3, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the issue
      description: What is not working correctly?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we recreate this issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to see?
  - type: textarea
    attributes:
      label: Proposed solution
      description: Do you have suggestions on how to fix this?
